{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '1'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'female','pclass' => '3'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '2'} = 1
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'male','pclass' => '3'} = 0
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '2'} = 0
{'sex' => 'female','pclass' => '1'} = 1
{'sex' => 'female','pclass' => '3'} = 0
{'sex' => 'male','pclass' => '1'} = 1
{'sex' => 'male','pclass' => '3'} = 0
